spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=timesheets
    name: postgres
    username: admin
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true